# Generated by Django 6.0.3 on 2026-03-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'foizli'), ('flex', 'aniq')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('gr', 'gram'), ('kg', 'kilogram'), ('ml', 'mill'), ('l', 'litr'), ('pc', 'dona')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
